### PR TITLE
Added Murzayeva.java class

### PR DESCRIPTION
**Pull request by Aziza526**
Added a class Murzayeva.java for number guessing game.

### CODE REVIEW

**Review by tccnw-it — CHANGES_REQUESTED** [review]
Need to remove public static void main from Murzayeva.  Program will not currently compile because of multiple entry points.  Also avoid cleaning up code with the automatic source formatting in code that is not COMPLETELY yours.  There have been many instances where working code is destroyed because of code cleanup in multi-file programs.

**Comment by Aziza526** [comment]
I have made the changes you suggested, could you check it please?

**Review by tccnw-it — APPROVED** [review]
Accepted.  You have completed part 4 of the Final Project.  All other parts of the Final Project should be submitted through Canvas.

**Comment by tccnw-it** [comment]
Already replied in GitHub. Thanks.

**Pull request closed without merging**
